### ISSUE TITLE
Soft reboot makes communication stop on telnet

### ISSUE THREAD

**Issue by RalphHogenbirk** [pycom/pycom-micropython#1]
When connected to a lopy or wipy2 (tested on 0.9.3.b2 and 0.9.4.b1) over telnet and a soft reboot is performed, the session gets stuck. It doesn't respond to any input. Doing the same thing over serial port is working correctly.

**Comment by danicampora** [comment]
Solved by: https://github.com/pycom/pycom-micropython/commit/0b659ead5a5d77cbe4d1f7e73c05cc4c710c9b38
