### ISSUE TITLE
API missing: wlan.bssid?

### ISSUE THREAD

**Issue by betabrain** [pycom/pycom-micropython#13]
### Version Information:
```python
(sysname='LoPy', nodename='LoPy', release='0.9.4.b1', version='bc42ea7 on 2016-11-14', machine='LoPy with ESP32')
```

### Feature Request:
I believe the `network.WLAN` object should have a way to query not just for the SSID, but also the BSSID of the current network.

```python
>>> wlan.bssid() # currently not available
b'\xff\xff\xff\xff\xff\xff'
```

**Comment by danicampora** [comment]
OK, we'll add it.

**Comment by danicampora** [comment]
Done here: https://github.com/pycom/pycom-micropython/commit/8862d5dee9745a62421a2b443d31a82144967f72
