### ISSUE TITLE
Support of pre-compiled Python scripts

### ISSUE THREAD

**Issue by robert-hh** [pycom/pycom-micropython#19]
Dear pycom team,
may I ask you to include the line:
`#define MICROPY_PERSISTENT_CODE_LOAD                     (1)`
by default in your esp32/mpconfigport.h file. That allows loading of files pre-compiled with mpy-cross from the MicroPython tool chain. Pre-compiled files not only load faster, but also do not need additional RAM for compiling.

Best Regards, Robert

**Comment by yahia13** [comment]
Can we have this in the new firmware?

**Comment by Xykon** [comment]
Closing this issue as this has been enabled.
