### ISSUE TITLE
Can not make WiPy build

### ISSUE THREAD

**Issue by robert-hh** [pycom/pycom-micropython#2]
Trying to build the version for WiPy in cc3200 fails with:
`../py/obj.h:33:22: fatal error: esp_attr.h: No such file or directory
`
This file is missing in the source tree.
Update: found it in /pycom-esp-idf
But then compiling ftp.c fails with the error.
`ftp/ftp.c:608:8: error: 'FILINFO' has no member named 'lfname'
`
It looks like you mixed non-matching trees.

**Comment by danicampora** [comment]
Thanks for the report. We will update the cc3200 port soon.

**Comment by livius2** [comment]
In current revision ( e1a0670 few minutes ago)
i got error when i try to make WIPY
bootloader/gpio.c: In function 'gpio_set_pull_mode':
bootloader/gpio.c:181:13: error: 'PIN_PULLUP_EN' is deprecated (declared at P:/msys32/esp-idf/components/esp32/include/soc/io_mux_reg.h:56) [-Werror=deprecated-declarations]
             PIN_PULLUP_EN(GPIO_PIN_MUX_REG[gpio_num]);

**Comment by danicampora** [comment]
Is that with the latest IDF from Espressif or with the one here: https://github.com/pycom/pycom-esp-idf ?

You should always user ours...

**Comment by livius2** [comment]
in pycom-esp-idf/docs/windows-setup.rst
there is step 2

> Step 2: Getting the esp-idf repository from github
