### ISSUE TITLE
newest firmware is not booted after flashing another custom firmware

### ISSUE THREAD

**Issue by ejpir** [pycom/pycom-micropython#21]
I have successfully flashed a custom built firmware that was built from this git. Booted without problems.

After removing the changes and reflashing a new firmware, the old firmware changes are still there and it seems the 2nd (newest) custom firmware is not loaded.

Tried to fix this by:
- change the makeversionhdr.py script to generate custom versions with "-nick" appended. no luck
- flash using serial. no luck
- flash using ftp. no luck

# header file (auto generated after modifying the makeversionhdr script)

```
/ This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.8.6-16-g7c37117-dirty-nick"
#define MICROPY_GIT_HASH "7c37117-dirty-nick"
#define MICROPY_BUILD_DATE "2016-11-21"
#define MICROPY_VERSION_MAJOR (1)
#define MICROPY_VERSION_MINOR (8)
#define MICROPY_VERSION_MICRO (6)
#define MICROPY_VERSION_STRING "1.8.6-nick"
```

# serial flash output

```
root@developer:/home/developer/esp32/pycom-micropython/esp32# export PATH=$PATH:/home/developer/esp32/xtensa-esp32-elf/bin
root@developer:/home/developer/esp32/pycom-micropython/esp32# make BOARD=LOPY LORA_BAND=USE_BAND_868 flash
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
Flashing project
esptool.py v2.0-dev
Connecting...
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Attaching SPI flash...
Configuring flash size...
Erasing flash...
Compressed 4096 bytes to 2888...
Wrote 4096 bytes (2888 compressed) at 0x00001000 in 0.0 seconds (effective 889.2 kbit/s)...
Hash of data verified.
Erasing flash...
Compressed 256 bytes to 125...
Wrote 256 bytes (125 compressed) at 0x00004000 in 0.0 seconds (effective 551.0 kbit/s)...
Hash of data verified.
Erasing flash...
Compressed 839248 bytes to 500400...
Wrote 839248 bytes (500400 compressed) at 0x00010000 in 7.9 seconds (effective 845.8 kbit/s)...
Hash of data verified.

Leaving...
```

How does the Lopy determine what the newest firmware is and how to force it to load the latest?

I am aware of the safeboot and P12 pin, but I am assuming this will not work either. The latest firmware should be loaded by default.

**Comment by ejpir** [comment]
@danicampora I got it to load the newest firmware by pulling P12 up and releasing it in the first 3 second window.

**Is this a bug? I thought it should boot the newest in normal mode as well.**

Now it is booting the newest firmware in normal mode, even after totally powering down.

Before doing the P12 thing it was not loading the latest firmware.

**Comment by danicampora** [comment]
Combining OTA updates with serial flasher updates gives estrange results. These two methods of flashing are not meant to be used together. That's why our serial flasher erases almost the entire flash (except for the file system and the LoRa MAC address), an the flashes the bootloader, the partition table.

**Comment by ejpir** [comment]
oke. I have had more luck since then when only using the serial flasher :)
