### ISSUE TITLE
in commit d1dd08b missing file esp_image_format.h

### ISSUE THREAD

**Issue by livius2** [pycom/pycom-micropython#34]
I do not know if this is finall commit
but in commit d1dd08b there is missing file esp_image_format.h
used in bootloader/bootloader.c

**Comment by danicampora** [comment]
You just need to update the IDF: https://github.com/pycom/pycom-esp-idf :-)

**Comment by livius2** [comment]
i see :)
sorry - i still forgot about dependencies between

**Comment by danicampora** [comment]
No problems :-)
