### ISSUE TITLE
LoPy sometimes uses FPort = 0 when sending data frames

### ISSUE THREAD

**Issue by ejpir** [pycom/pycom-micropython#36]
Using a LoPy, custom firmware (nothing but printf statements added) built from Github.

When sending data frames (lorawan messages) modlora.c sometimes uses Fport = 0. Should only be used for MAC commands. Thanks to htdvisser of TTN for helping me with this.

Have mainly seen it happen when messages are bigger than 4 bytes, but unsure about this.

# Settings
- SF=7
- DR=5
- coding=4/5
- auth = OTAA
- mode = LORAWAN

# version
`MicroPython v1.8.6-15-g50c448d-dirty`

# result

Messages/frames are not valid and not shown in MQTT of the broker/backend.

# workaround / fix
- modify esp32/mods/modlora.c

```
mcpsReq.Req.Unconfirmed.fPort = #integerNumberAbove0#
mcpsReq.Req.Confirmed.fPort = #integerNumberAbove0#
```

**Comment by danicampora** [comment]
@ejpir Thanks!

**Comment by danicampora** [comment]
Done here: https://github.com/pycom/pycom-micropython/commit/2c25e0e2185893e14cbc64df8aadc5c864941f7a

**Comment by ejpir** [comment]
great! 👍
