### ISSUE TITLE
I2C Clock Stretching

### ISSUE THREAD

**Issue by brotherdust** [pycom/pycom-micropython#45]
Per @abiliojr, I am placing this here as a feature request. [Source forum post.](https://forum.pycom.io/topic/331/i2c-clock-stretching)

Hi there Pycom folks! Hope you had a restful weekend!

I was hoping you could shed some light on something I've been banging my head on today. I am trying to implement the Bosch BNO055 IMU fusion sensor based on the Adafruit breakout: https://www.adafruit.com/products/2472

What's happening is that I can't get the sensor to communicate on the I2C bus at baud rates any higher than 1000 (ugh). According to the datasheet (see table 4.8: I2C Timings), the sensor supports fast mode (400,000).

After going through the datasheet a few more times, the only thing that really stands out to me is that this sensor uses I2C "clock stretching". This correlates with how the official Adafruit Arduino driver sets up the sensor: https://github.com/adafruit/Adafruit_BNO055/blob/master/Adafruit_BNO055.cpp#L60

The stock I2C driver in micropython seems to know about clock stretching, too:
https://github.com/pycom/pycom-micropython/blob/master/extmod/machine_i2c.c#L57

But, in the ESP32 I2C driver, it would seem these functions are completely (and conspicuously) absent. According to http://www.i2c-bus.org/clock-stretching/, "Clock stretching sounds a bit odd but is common practice."

So, my esteemed Pycom team, do you have a suggested workaround or any plans to implement this? It would seem, at least according to the available data, that the I2C functions for ESP32 would not be complete without it.

Thank you!

**Comment by danicampora** [comment]
@brotherdust Thanks for the report. The I2C drivers will be much improved for the 1.0 release in mid december. 400KHz clock will work there for sure, and clock stretching will be supported.

**Comment by brotherdust** [comment]
Thank you!
