### ISSUE TITLE
socket.IPPROTO_SEC missing from socket library

### ISSUE THREAD

**Issue by RalphHogenbirk** [pycom/pycom-micropython#52]
The example code from the ussl library (https://docs.pycom.io/pycom_esp32/library/ussl.html#module-ussl):
```
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM, socket.IPPROTO_SEC)
```

Results in a 'no attribute 'IPPROTO_SEC'' error. Probably already known to be missing, but added the issue for tracking.

Board: wipy2.0, firmware 1.0.1.b1

**Comment by danicampora** [comment]
This is only needed for the WiPy 1.0
