### ISSUE TITLE
esp32/bootloader: compile fails

### ISSUE THREAD

**Issue by robert-hh** [pycom/pycom-micropython#53]
Compiling fails with the error:
```
bootloader/bootloader.c: In function 'unpack_load_app':
bootloader/bootloader.c:581:17: error: implicit declaration of function 'get_sp' [-Werror=implicit-function-declaration]
                 sp = (intptr_t)get_sp();

```
There seems no prototype for the function get_sp(), and also no function get_sp(). Both the micropthon and esp_idf clones are updated.

**Comment by danicampora** [comment]
Thanks, fixed with https://github.com/pycom/pycom-esp-idf/commit/8c13f3f23457b23c32760d780ffd3320f5732616
