### ISSUE TITLE
unix compile failed on ubuntu - missing esp_attr.h

### ISSUE THREAD

**Issue by diginfo** [pycom/pycom-micropython#66]
Just tried compiling on Ubuntu and it failed.

In file included from ../lib/timeutils/timeutils.c:28:0:
../py/obj.h:33:22: fatal error: esp_attr.h: No such file or directory
 #include "esp_attr.h"

I also checked and can't find the esp_attr.h in py folder ??

**Comment by diginfo** [comment]
OK, I fixed this by downloading from here:

https://raw.githubusercontent.com/espressif/esp-idf/master/components/esp32/include/esp_attr.h

**Comment by nevercast** [comment]
Where did you put this file? esp-idf and pycom-idf both have this file. Since I already have pycom-idf available can I just include it?
