### ISSUE TITLE
LoPy: using P15 crashes

### ISSUE THREAD

**Issue by faif** [pycom/pycom-micropython#8]
* The Pycom board you are using: LoPy
* The firmware version you are using: 0.9.4.b1
* Exact steps to cause this issue. Execute the following code:
```
import machine
machine.Pin('P15')
```
* What you expected
    * to get the Pin value
* What happened instead
    * Crash (Guru Meditation) and the CPU halted

**Comment by lonetech** [comment]
Also affects P16. The problem occurs running init(), you can still access the pin objects within machine.Pin.module or machine.Pin.exp_board.

**Comment by lonetech** [comment]
Erm.. I accidentally fixed this, it seems bug #10 was the root cause. That affected P15=GPIO38, which would poke at GPIO6, and P16=GPIO39, which would poke at GPIO7. I'm not sure what those do, they're not in the LoPy pin map.
