### ISSUE TITLE
Sync project from Pymakr fails most of the time

### ISSUE THREAD

**Issue by JF002** [pycom/pycom-micropython#86]
I'm using a Lopy with firmware version 1.6.5.b1. I have a project  with 5 folders and 15 files (46Ko).
Nearly every time I try to sync the project with Pymakr, it fails ('sync failed').
I just reset the board and click on the Sync button, nothing special.

Note that I manage to upload the files to the flash memory using Wifi and Filezilla.

**Comment by Xykon** [comment]
Closing this issue as it's not firmware related.

**Comment by nevercast** [comment]
@JF002 this might be a better place: https://forum.pycom.io/category/17/software-tools
