### ISSUE TITLE
ADC working in 10 bits

### ISSUE THREAD

**Issue by RobertoBiundo** [pycom/pycom-micropython#9]
It seems that the ADC is working in 10 bits mode and not in the required 12 bits
To replicate the error

`from machine import ADC`
`adc = machine.ADC(bits=12)`
`pin = adc.channel('G5')`
`pin()`

On setting the line G5 to 3v3 the max value reported is 1023 (10 bits max value) when it should be 4095 (12 bits max value)

**Comment by abiliojr** [comment]
fixed here: 2ff11b7fa189052e25092eb1abcef5bb929ccdce
