### ISSUE TITLE
LoRaWAN init, tx_retries bug

### ISSUE THREAD

**Issue by timrid** [pycom/pycom-micropython#90]
Hi, im using a LoPy Board. I found a Bug in the init routine of the lorawan object.

In the function `lora_init_helper(...)` (modlora.c) the wrong array element is given to `tx_retries` as you can see in the following code snippet: 

```
cmd_data.info.init.adr = args[10].u_bool;
cmd_data.info.init.public = args[11].u_bool;
cmd_data.info.init.tx_retries = args[11].u_int;
```

**Comment by danicampora** [comment]
Fixed. Thanks!
